from __future__ import annotations

import logging
import os
import stat
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

RAGPIPE_BEGIN = "# RAGPIPE BEGIN"
RAGPIPE_END = "# RAGPIPE END"

HOOK_TEMPLATE = f"""\
{RAGPIPE_BEGIN}
# Auto-generated by RAGPipe. Do not edit between markers.
ragpipe index . --chunk-size {{chunk_size}} > /dev/null 2>&1
echo "[ragpipe] index updated (output: {{output_path}})"
{RAGPIPE_END}
"""


def _resolve_hooks_dir(repo_path: str) -> Path:
    repo = Path(repo_path).resolve()
    hooks_dir = repo / ".git" / "hooks"
    if not hooks_dir.is_dir():
        raise FileNotFoundError(f"No .git/hooks directory found at {hooks_dir}")
    return hooks_dir


def _find_ragpipe_section(content: str) -> tuple[int, int] | None:
    begin_idx = None
    end_idx = None
    lines = content.splitlines(True)
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == RAGPIPE_BEGIN and begin_idx is None:
            begin_idx = i
        elif stripped == RAGPIPE_END and begin_idx is not None:
            end_idx = i + 1
            break
    if begin_idx is not None and end_idx is not None:
        return (begin_idx, end_idx)
    return None


def _has_ragpipe_marker(hook_path: Path) -> bool:
    if not hook_path.exists():
        return False
    content = hook_path.read_text(encoding="utf-8")
    return _find_ragpipe_section(content) is not None


def install_hook(
    repo_path: str = ".",
    hook_type: str = "post-commit",
    output_path: str = "./ragpipe_output.json",
    chunk_size: int = 512,
) -> Path:
    hooks_dir = _resolve_hooks_dir(repo_path)
    hook_file = hooks_dir / hook_type

    if _has_ragpipe_marker(hook_file):
        logger.warning(
            "RAGPipe hook already exists in %s. Removing old section and re-prepending.",
            hook_file,
        )
        remove_hook(repo_path, hook_type)

    section = HOOK_TEMPLATE.format(chunk_size=chunk_size, output_path=output_path)

    if hook_file.exists():
        existing = hook_file.read_text(encoding="utf-8")
        new_content = section.rstrip() + "\n" + existing.lstrip()
        if not existing.endswith("\n"):
            new_content += "\n"
    else:
        new_content = "#!/bin/sh\n" + section + "\n"

    hook_file.write_text(new_content, encoding="utf-8")

    current_mode = hook_file.stat().st_mode
    hook_file.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    logger.info("Installed %s hook at %s", hook_type, hook_file)
    return hook_file


def remove_hook(repo_path: str = ".", hook_type: str = "post-commit") -> None:
    hooks_dir = _resolve_hooks_dir(repo_path)
    hook_file = hooks_dir / hook_type

    if not hook_file.exists():
        logger.info("No %s hook found at %s — nothing to remove.", hook_type, hook_file)
        return

    content = hook_file.read_text(encoding="utf-8")
    section = _find_ragpipe_section(content)

    if section is None:
        logger.info("No RAGPipe markers found in %s.", hook_file)
        return

    begin, end = section
    lines = content.splitlines(True)
    remaining = lines[:begin] + lines[end:]

    remaining_text = "".join(remaining).strip()

    if not remaining_text or remaining_text == "#!/bin/sh":
        hook_file.unlink()
        logger.info("Removed %s hook file (empty after removing RAGPipe section).", hook_file)
    else:
        hook_file.write_text(remaining_text + "\n", encoding="utf-8")
        logger.info("Removed RAGPipe section from %s.", hook_file)


def list_hooks(repo_path: str = ".") -> list[dict[str, Any]]:
    hooks_dir = _resolve_hooks_dir(repo_path)
    results: list[dict[str, Any]] = []

    if not hooks_dir.exists():
        return results

    for hook_file in sorted(hooks_dir.iterdir()):
        if not hook_file.is_file():
            continue
        content = hook_file.read_text(encoding="utf-8")
        section = _find_ragpipe_section(content)
        if section is None:
            continue

        begin, end = section
        section_text = "".join(content.splitlines(True)[begin:end])

        output_path: str | None = None
        for line in section_text.splitlines():
            line = line.strip()
            if line.startswith("echo") and "output:" in line:
                paren = line.index("output:") + len("output:")
                rest = line[paren:].strip()
                rest = rest.strip('"').strip("'").rstrip(")")
                output_path = rest.strip()
                break

        results.append(
            {
                "hook_type": hook_file.name,
                "installed": True,
                "output_path": output_path,
            }
        )

    return results
